migrations:
	@echo "Creating database migrations..."
	uv run manage.py makemigrations

migrate:
	@echo "Running database migrations..."
	uv run manage.py migrate

run:
	@echo "Starting the development server..."
	uv run manage.py runserver

createsuperuser:
	@echo "Creating a superuser..."
	uv run manage.py createsuperuser
